### ISSUE TITLE
Reproducibility of Published Example

### ISSUE THREAD

**Issue by sheentidadul** [ElsevierSoftwareX/SOFTX-D-22-00047#1]
I want to study this Python program. First, I'd like to reproduce the example given in your journal https://www.sciencedirect.com/science/article/pii/S235271102200067X.

![image](https://github.com/ElsevierSoftwareX/SOFTX-D-22-00047/assets/129776355/9bcd4b6b-3d40-42d2-a3cd-f6f6e7e057a5)

However, I get this error when generating polygons. What seems to be the problem?

Traceback (most recent call last):
  File "C:\Users\sheen\Downloads\SOFTX-D-22-00047-master\main_Cloud2FEM.py", line 400, in genpolygons_clicked
    mct.polygs, invalidpolygons = cp.make_polygons(minwthick, mct.zcoords, mct.cleanpolys)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sheen\Downloads\SOFTX-D-22-00047-master\Cloud2Polygons.py", line 267, in make_polygons
    newpgon = sg.Polygon(polyline)  # Just converted a polyline into the shapely Polygon data structure
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sheen\AppData\Local\Programs\Python\Python311\Lib\site-packages\shapely\geometry\polygon.py", line 230, in __new__
    shell = LinearRing(shell)
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\sheen\AppData\Local\Programs\Python\Python311\Lib\site-packages\shapely\geometry\polygon.py", line 93, in __new__
    coordinates = np.array([_coords(o) for o in coordinates])
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: iteration over a 0-d array

![image](https://github.com/ElsevierSoftwareX/SOFTX-D-22-00047/assets/129776355/537418a9-9afa-4603-8330-0eb3fcb7e87d)

**Comment by Reajo** [comment]
Hi, I had this problem too, have you solved it yet?

**Comment by sheentidadul** [comment]
I haven't yet.

**Comment by Reajo** [comment]
Okay, thanks for the reply. Although I didn't figure out what was causing the problem, I found that the latest code released by the author can reproduce the cases in the paper properly, so I hope that helps if you still need it!
https://github.com/gcastellazzi/Cloud2FEM-portable?tab=readme-ov-file
